### ISSUE TITLE
Name clash for guard.nvim

### ISSUE THREAD

**Issue by xiaoshihou514** [nvim-neorocks/nurr#26]
I added guard.nvim to [luarocks](https://luarocks.org/modules/xiaoshihou514/guard.nvim) just now, but I can't add it to the root manifest because the namespace is clashing. Is it possible to remove the auto generated rock so I can add mine in its place?
This would be a breaking change for those who are using rocks.nvim to install guard.nvim right now, and I am unsure of the consequences. (My rockspec does not have guard-collection as a dependency)

**Comment by mrcjkb** [comment]
What's your reason for wanting to remove the dependency?
I'm aware that it's optional, but most users are going to want it and having it installed shouldn't have a negative impact (e.g. on startup time).
Or does it clash with your own collection somehow?

**Comment by xiaoshihou514** [comment]
I just haven't bothered porting `guard-collection` to luarocks yet, and it doesn't seem to work with the current auto generated `guard-collection` (by using the luarocks-tag-release and the `with` param).

**Comment by xiaoshihou514** [comment]
https://github.com/nvimdev/guard.nvim/actions/runs/11192393006/job/31116547375

**Comment by mrcjkb** [comment]
> it doesn't seem to work with the current auto generated guard-collection

luarocks can't find it because guard-collection doesn't have a semver release, and it's not using the `--dev` cli argument to search the dev manifest (it's not advised for semver packages to depend on dev/scm packages).

I'll remove guard.nvim from the nurr and will remove the luarocks package from the root manifest. 
You'll have to add your version manually from your luarocks account.

**Comment by xiaoshihou514** [comment]
Cool! Thanks for understanding :)

**Comment by mrcjkb** [comment]
removed guard.nvim and guard-collection.
